// No need to import types - this is plain JS now

export const entrepreneurs = [
  {
    id: 1,
    name: 'Usha',
    story: "She is a creative person who enjoys turning her ideas into reality. Here, she used everyday items to create a stunning decorative piece. She hand-carved a little bird out of wood, threaded a used bangle with attractive gold designs, made cute little flowers from paper, and to finish off she embellished the piece with pearls and beads she already had at home. It's the ideal illustration of transforming ordinary materials into something unique. Only a month ago, she started bringing her ideas to life. She currently sells most of her handmade items to locals, charging between ₹250 and ₹300. Although her reach is still small, word-of-mouth has begun passion with friends, family, and the families she serves. Her primary source of income now comes from her personal network, but she hopes to reach a wider audience in the future.",
    profileImageUrl: '/Usha-img.webp',
    whatsappNumber: '919876543211',
  },
  {
    id: 2,
    name: 'Koushalya',
    story: "Koushalya loves to make handcrafted artificial flowers using simple materials like paper, broomsticks, and foam bases. Each arrangement features bright red roses with green leaves and decorative accents, designed to bring elegance and charm to living rooms, dining tables, or office spaces. Unlike real flowers, these creations are long-lasting, maintenance-free, and make for thoughtful gifts on special occasions. Her problem is that she works a lot in several households and lives far from the city, limiting her ability to sell directly and she does not know how else to sell her products. Her handcrafted pieces are priced affordably, starting at ₹150 for simpler designs and going up to ₹450 for more detailed and complex arrangements.",
    profileImageUrl: '/koushalya-img.webp',
    whatsappNumber: '919876543211',
  },
  {
    id: 3,
    name: 'Geeta',
    story: "Geeta has a deep passion for turning unused household materials into beautiful handcrafted pieces. For this rustic hanging bird nest, she creatively transformed a large plastic cap into the base, covered it with rope sourced from her village, and added coconut husk on the outside to give it a natural look and pleasant aroma. Adorned with miniature decorative birds, this unique piece brings a nature-inspired charm to any space and can be hung on walls or near windows to create a warm, inviting atmosphere. Although making such crafts is currently just a passion for her, Geeta dreams of selling her creations one day, but her husband does not allow her to leave the house for such purposes.",
    profileImageUrl: '/geeta-img.webp',
    whatsappNumber: '919876543212',
  },
  {
    id: 4,
    name: 'Anu',
    story: "Anu enjoys creating beautiful handcrafted pieces in her free time. She recently made a hand-embroidered fabric bookmark with intricate stitching in colorful threads. It is a functional yet artistic accessory that I personally adore as a book lover. Her bookmarks are useful tools and also collectible items that make thoughtful, handmade gifts reflecting creativity and cultural artistry. Although she dreams of branching out into more personalized products like pillowcases and stuffed animals, her resources are currently limited. Therefore, she focuses on what she can create with care and detail. Priced affordably at ₹200 to ₹250 per bookmark, her work is accessible and meaningful, carrying the warmth of something made by hand with love.",
    profileImageUrl: '/anu-img.webp',
    whatsappNumber: '919876543213',
  },
  {
    id: 5,
    name: 'Anusha',
    story: "Anusha is an independent business women who creates unique handmade jewelry, including necklaces and bracelets crafted from amethyst stones. Each piece is carefully tied together with strong thread, a process that takes her about 30–35 minutes since she does everything manually. She prices her necklaces at ₹450, occasionally offering discounts of up to 15%, and her bracelets are priced at ₹250. She started this business due to her fascination with stones and a love for jewellery.",
    profileImageUrl: '/anusha-img.webp',
    whatsappNumber: '919876543214',
  },
  {
    id: 6,
    name: 'Sai Laxmi',
    story: "Sai Laxmi specializes in creating beautiful handbags made from rich Banarasi silk fabric. Each bag is carefully handcrafted, featuring traditional motifs and zari designs, and finished with expert karigar stitching for durability and elegance. On average, it takes her nearly two hours to complete a single piece, and she offers them at an affordable price of around ₹400.",
    profileImageUrl: '/sri-laxmi-img.webp',
    whatsappNumber: '919876543215',
  },
  {
    id: 7,
    name: 'Padma',
    story: "Padma specializes in creating exquisite Meenakari artwork on marble plates. The process is highly detailed and time-intensive that can take her up to two full days to complete a single piece. She begins by cutting and shaping raw marble into a plate, and then carefully for each marble plate she hand-paints different traditional Meenakari designs creating variety. The marble plate is extremely durable preventing the Meenakari art from fading making it very efficient although the plate should be handled with care as it is delicate. Her marble plate is priced at ₹2500, and her love for Meenakari art comes from her mother, who originally started this business. She is determined to carry forward this legacy while also expanding her reach through online platforms, hoping to share her traditional artistry with a wider audience.",
    profileImageUrl: '/Padma-img.webp',
    whatsappNumber: '919876543216',
  },
  {
    id: 8,
    name: 'Rehana Begum',
    story: "Rehana Begum makes unique necklaces crafted from belts, beads, and camel bone. She uses the belt as the base, adds beads for decoration, and she divides each design with a camel bone. On these bone elements, she hand-draws creative designs, giving every piece a unique and personal touch. Her necklaces are priced from ₹1200 onwards. Rehana usually dedicates her Saturdays and Sundays to making these pieces, working alongside her sister who helps out selling these in their village.",
    profileImageUrl: '/rehana-img.webp',
    whatsappNumber: '919876543217',
  },
  {
    id: 9,
    name: 'Kajal',
    story: "Kajal creates unique pottery using a special type of mud sourced from her village. She makes many types of products. One of her standout products is the Water Whistle, crafted from this mud and shaped with precision. This design produces a whistling sound only when water is added, making it special and distinctive. Each water whistle is priced at ₹100. She also makes a variety of religious and decorative pieces, including Ganesha idols, brushed with gold or silver dust to enhance their beauty. These pieces are priced around ₹300 each. She also designs handcrafted earrings made using pottery that are both stylish and affordable, available at ₹200 for a pair. Every piece Kajal creates is handmade that are perfect for gifting, home decor, or personal use.",
    profileImageUrl: '/kajal-img.webp',
    whatsappNumber: '919876543218',
  },
  {
    id: 10,
    name: 'Sujitha',
    story: "While serving time in jail, Sujitha started to make decorative pieces of yarn. She began tying and shaping yarn into beautiful bird-like figures. After she got out she decided to start this business by herself because she faced a lot of difficulties finding a job. She recently opened a small shop, where she sells these handcrafted yarn decorations and she wants to start marking more things with yarn. Each piece is normally priced around ₹150 depending on its complexity. Her main source of revenue is from the local people that pass by.",
    profileImageUrl: '/Sujitha-img.webp',
    whatsappNumber: '919876543219',
  },
  {
    id: 11,
    name: 'Kavitha',
    story: "Kavitha is extremely spiritual and loves art. In school she used to take painting classes and realised how much she loves Tanjore painting, a traditional and intricate form of Indian art. When she graduated school she immediately started her business of Tanjore art. Her process is meticulous, First she prepares the wooden background herself, paints it black, and then carefully finishes the artwork with 24-carat gold foil to bring out its divine beauty.Each painting often takes nearly two months to complete because of the immense detailing and patience required. Kavitha creates many pieces in different sizes and normally her paintings for medium sized is priced starting from ₹3300.",
    profileImageUrl: '/Kavitha-img.webp',
    whatsappNumber: '919876543220',
  },
];

export const products = [
  {
    id: 1,
    name: 'Hand-carved Bird Decor',
    price: 275,
    category: 'Home Decor',
    imageUrl: '/Home-decor-img.webp',
    videoUrl: '/Home-decor-video.mov',
    entrepreneurId: 1,
  },
  {
    id: 2,
    name: 'Artificial Red Rose Bouquet',
    price: 300,
    category: 'Artificial Flowers',
    videoUrl: '/artifical-flower-video.mov',
    imageUrl: '/artifical-flower-img.webp',
    entrepreneurId: 2,
  },
  {
    id: 3,
    name: 'Rustic Hanging Bird Nest',
    price: 350,
    category: 'Handicrafts',
    videoUrl: '/bird-nest-video.mov',
    imageUrl: '/bird-nest-img.webp',
    entrepreneurId: 3,
  },
  {
    id: 4,
    name: 'Hand-Embroidered Bookmark',
    price: 225,
    category: 'Embroidery',
    videoUrl: '/embroidered-bookmark-video.mov',
    imageUrl: '/embroidered-bookmark-img.webp',
    entrepreneurId: 4,
  },
  {
    id: 5,
    name: 'Amethyst Stone Necklace',
    price: 450,
    category: 'Jewellery',
    videoUrl: '/jewellery-video.mov',
    imageUrl: '/jewellery-img.webp',
    entrepreneurId: 5,
  },
  {
    id: 6,
    name: 'Banarasi Silk Handbag',
    price: 400,
    category: 'Bags',
    videoUrl: '/handbag-video.mov',
    imageUrl: '/handbag-img.webp',
    entrepreneurId: 6,
  },
  {
    id: 7,
    name: 'Meenakari Marble Plate',
    price: 2500,
    category: 'Art',
    videoUrl: '/marble-plate.mov',
    imageUrl: '/marble-plate-img.webp',
    entrepreneurId: 7,
  },
  {
    id: 8,
    name: 'Camel Bone Necklace',
    price: 1200,
    category: 'Jewellery',
    videoUrl: '/necklaces-video.mov',
    imageUrl: '/necklaces-img.webp',
    entrepreneurId: 8,
  },
  {
    id: 9,
    name: 'Pottery Water Whistle',
    price: 100,
    category: 'Pottery',
    videoUrl: '/bird-water.mov',
    imageUrl: '/Bird-water-img.webp',
    entrepreneurId: 9,
  },
  {
    id: 10,
    name: 'Golden Ganesha Idol',
    price: 300,
    category: 'Pottery',
    videoUrl: '/ganesha-video.mov',
    imageUrl: '/ganesha-img.webp',
    entrepreneurId: 9,
  },
  {
    id: 11,
    name: 'Handcrafted Pottery Earrings',
    price: 200,
    category: 'Jewellery',
    imageUrl: '/earing-img.webp',
    entrepreneurId: 9,
  },
  {
    id: 12,
    name: 'Decorative Yarn Bird',
    price: 150,
    category: 'Handicrafts',
    imageUrl: '/birds-img.webp',
    entrepreneurId: 10,
  },
  {
    id: 13,
    name: 'Tanjore Painting (Medium)',
    price: 3300,
    category: 'Art',
    imageUrl: '/painting-img.webp',
    entrepreneurId: 11,
  },
];
